version: '3.8'
services:
  dev-db:
    image: postgres:17
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nguyendat2003
      POSTGRES_DB: wallet_db
    networks:
      - freecodecamp

networks:
  freecodecamp:
